Update the Readme for the lib-megashark
Scille/megashark-lib pull request #19
Opened 2024-04-26 07:01 UTC by fabienSvtr

closes #13

2024-04-26 07:13 UTC, Ironicbay requested changes

2024-04-26 07:13 UTC, Ironicbay commented on README.md
> +The megashark-lib library is a UI component library. It is used to centralise all the elements that will be reused throughout the various Parsec projects (images, typography, UI components, global tr
```suggestion
The megashark-lib library is a UI component library. It is used to centralize all the elements that will be reused throughout the various Parsec projects (images, typography, UI components, global translation).
```

2024-04-26 07:13 UTC, Ironicbay commented on README.md
> +**lib**: includes all the libraryce components that you want to have in common in the library.
`libraryce` ?

2024-04-26 07:13 UTC, Ironicbay commented on README.md
> +> In the **megashark-lib**:
```suggestion
> In **megashark-lib**:
```

2024-04-26 07:13 UTC, Ironicbay commented on README.md
> +> In the **megashark-lib**
```suggestion
> In **megashark-lib**
```

2024-04-26 07:13 UTC, Ironicbay commented on README.md
> +> In the **parsec-cloud**
```suggestion
> In **parsec-cloud**
```

2024-04-26 07:13 UTC, Ironicbay commented on README.md
> +> In the **parsec-cloud**
```suggestion
> In **parsec-cloud**
```

2024-04-26 07:13 UTC, Ironicbay commented on README.md
> +> In the **parsec-cloud**
```suggestion
> In **parsec-cloud**
```

2024-04-26 07:27 UTC, Ironicbay approved these changes

2024-04-26 10:00 UTC, Max-7 requested changes

2024-04-26 10:00 UTC, Max-7 commented on README.md
> +npm run web:open //web
Comments use `#`, not `//`

2024-04-26 10:00 UTC, Max-7 commented on README.md
> +npm run lib:local:stop
Renamed to `megashark:local:stop`

2024-04-26 10:01 UTC, NicoTuxx requested changes

2024-04-26 10:01 UTC, NicoTuxx commented on README.md
> +The megashark-lib library is a UI component library. It is used to centralize all the elements that will be reused throughout the various Parsec projects (images, typography, UI components, global tr
```suggestion
The megashark-lib is a UI component library. It is used to centralize all the elements that will be reused throughout the various Parsec projects (images, typography, UI components, global translation).
```

2024-04-26 10:09 UTC, NicoTuxx requested changes

2024-04-26 10:09 UTC, NicoTuxx commented on README.md
> +```
Installation needs npm install too

2024-04-26 10:09 UTC, NicoTuxx commented on README.md
> +This allows you to see changes made to the library and see them displayed in real time in the `parsec-cloud` project. Please follow all the commands in the order below.
```suggestion
This allows you to see changes made to the library and see them displayed in real time in the project using this library. Please follow all the commands in the order below.
```

2024-04-26 11:22 UTC, Max-7 commented on README.md
> +When you push on `master` → This creates a new version of the library.
Not really, resyncs should not be done all the time, they should be planned, with a tag and everything. The process of creating a tag (or a "new version") does not need to be detailled, it's up to the maintainer.

2024-04-29 15:55 UTC, NicoTuxx requested changes

2024-04-29 15:55 UTC, NicoTuxx commented on README.md
> +`npm link lib-megashark`: allows you to link the lib-megashark library (installed from the machine to github)
```suggestion
`npm link megashark-lib`: allows you to link the megashark-lib library (installed from the machine to github)
```

2024-04-29 15:55 UTC, NicoTuxx commented on README.md
> +npm run web:open#web
```suggestion
npm run web:open
```

2024-04-29 16:00 UTC, NicoTuxx approved these changes

2024-04-29 16:11 UTC, Max-7 approved these changes

2024-04-29 16:42 UTC, merged