Phone number validation (libphonenumber-js & MsPhoneNumberInput)
Scille/megashark-lib pull request #98
Opened 2024-07-04 20:24 UTC by NicoTuxx

2024-07-05 04:20 UTC, Max-7 requested changes

2024-07-05 04:20 UTC, Max-7 commented on lib/common/validation/phoneNumber.ts
> +import { IValidator, ValidationResult, Validity } from '@lib/common/validation';
Put those in a `types.ts` and import the file directly, not the module. This creates a circular import, I'm surprised the linter doesn't complain.

2024-07-05 04:20 UTC, Max-7 commented on lib/components/ms-input/MsPhoneNumberInput.vue
> +import { MsInput } from '@lib/components';
Import the full file from inside the module.

2024-07-05 04:20 UTC, Max-7 commented on src/views/HomePage.vue
> +    case 'fr':
`getLocale()` returns `fr-FR` or `en-US`.

2024-07-05 09:55 UTC, NicoTuxx commented
PR is suspended for now (other priorities on the project), however to finish it, take a look at this example to fix the usage of the validator:

You can make a closure for this:
```
 const wordValidator = ((word: string): (value: string) => Promise<ValidationResult> => {
   var validator = async function (value: string): Promise<ValidationResult> {
     return { validity: word === value ? Validity.Valid : Validity.Invalid };
   }
   return validator;
 });
```

And use it like this:
` <ms-input :validator="wordValidator('parsec')" />`
Returns Valid if input is strictly equal to 'parsec'.
Note: there seems to be a bug at focus loss, the model seems to reset, no idea why though.

2024-07-25 11:56 UTC, Max-7 approved these changes

2024-07-25 12:00 UTC, merged